dist: trusty
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:webupd8team/java'
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew

install: echo "skip 'gradle assemble' step"
script: travis_wait ./gradlew build deployNodes --console=plain
after_failure: cat /home/travis/build/manosbatsis/corbeans-yo-cordapp/server/build/reports/tests/integrationTest/index.html
