dist: trusty
language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: required
services:
  - docker

before_install:
  - chmod +x gradlew

install: echo "skip 'gradle assemble' step"
script: travis_wait ./gradlew build --console=plain
after_failure: cat /home/travis/build/manosbatsis/corbeans-yo-cordapp/server/build/reports/tests/integrationTest/index.html
